### ISSUE TITLE
fcl error

### ISSUE THREAD

**Issue by zhiansht** [topskychen/voxelizer#3]
l aready installed fcl from git.but l still get this error
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   atomic
--   thread
--   date_time
--   filesystem
--   system
--   unit_test_framework
-- checking for module 'fcl'
--   package 'fcl' not found
-- checking for module 'libfcl'
--   package 'libfcl' not found
CMake Error at CMakeLists.txt:32 (message):
  Libfcl is required by Voxelizer

# locate libfcl
/root/src/fcl/build/lib/libfcl.so
/root/src/fcl/build/lib/libfcl.so.0.6
/root/src/fcl/build/lib/libfcl.so.0.6.0
/usr/local/lib64/libfcl.so
/usr/local/lib64/libfcl.so.0.6
/usr/local/lib64/libfcl.so.0.6.0

why????

**Comment by topskychen** [comment]
It seems pkg-config can not find fcl library. Please try `pkg-config --cflags fcl`, and see what is the output.
It is suggested to use fcl with version 0.3.3. You can install with following lines:
```
git clone https://github.com/flexible-collision-library/fcl.git
git checkout tags/0.3.3
```
Most importantly, don't forget to use `build install` for fcl.
