### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Bit00009** [topskychen/voxelizer#8]
Hi there Chen! (@topskychen )
Very nice project!
The only issue I faced using your code was the program has random crashes, I tried to debug and find the issue sometimes getting voxel size `(double)(*_halfUnit)[0] * 2` throw a null and sometimes `(*_meshVoxLB)[0]` throws null error. 

I searched over the net and it seems its an act of **boost::asio.**
Can you please take a look and try a fix?

Your app is extremely fast ( 2 million voxel in 200ms ) but it crash like 2 in 3 run.

Also a very small note, you mentioned in README : 
> **It supports stl files only now.** 

But you're using **assimp** and it supports lots of formats.
It's enough to use **inputmesh.obj** instead of **inputmesh.stl** and it works just fine!

Regards,
Ultran

**Comment by topskychen** [comment]
Hi Ultran,

Could you give me an example file that you have issue with? and what is the use case or command line you are using? My local file works fine. I am happy to fix it if possible.

Thanks for the suggestion! Please have a try on the branch v2. It supports more formats and should be easier to use with cleaner arguments. For instance, `./bin/voxelizer --input=../data/ironman.obj --output=../playground/ironman_2.binvox --grid_size=256 --verbose=on`.

Regards,
Qian

**Comment by Bit00009** [comment]
Hi @topskychen ,
I tried version 2 and still error happens but this time it looks it's not random and it happens in `RandomPermutation` and `FillYZ `function , it still randomly happens on objects but it always crash on a sphere object input.

I made a ready-to-build solution with error issue it's for Visual Studio 2019 and Win64 , all dependencies are built and included.
Here you can get it :
https://easyupload.io/c4sutj
( File is only for 30 days - I'll re-upload if you couldn't catch it)

Also why new version gird is limited to 1024 is it possible to remove the limitation?

I added a marching cube and cubic mesher and  exporter to you voxelizer if you're interested I can make a pull request.

Be safe,
Ultran

**Comment by topskychen** [comment]
Hi Ultran,

I tried your objects, i.e., sphere.obj, teapot.obj and torus.obj. Both sphere and torus work perfectly to me. While for teapot, I found there are two meshes after optimization (I am using aiProcess_OptimizeGraph | aiProcess_OptimizeMeshes while loading the obj using Assimp), and the mesh 0 has faces with [primitive type of line](http://assimp.sourceforge.net/lib_html/mesh_8h.html#ac352902280db7c3bd8ba64c133b7f03fa724184f90f0e408b903d07aed39914b4). The voxelizer will crash when running on this mesh, since I am assuming the primitive type is triangle, i.e., 3 points. The mesh 1 for teapot is with triangle type, so the voxelizer can work on it. Please check the following screenshot.

![image](https://user-images.githubusercontent.com/1005777/86493404-0686b880-bda4-11ea-8af0-39a5963c3b91.png)

I have updated the version 2 to check the primitive type for mesh face, please have a try.

While in your description, you will crash on the sphere object, but I am working fine. One possibility is I am running on Mac (version: 10.15.5). Sorry that I don't have a Windows system on hand for testing.

The limitation of 1024 is due to the usage of unsigned int32 to compactly represent a (x,y,z) index. I can get rid of this limitation by increasing to int64 if you really need more than 1024 granularity.

"I added a marching cube and cubic mesher and exporter to you voxelizer if you're interested I can make a pull request." Any new feature is welcome!

Regards,
Qian

**Comment by Bit00009** [comment]
Hi @topskychen ,
I was testing entire night to earn some information.

It seems version 2 is more stable and crash is not random anymore like works one time and crash another time it works or it doesn't , Crash happens in **solid voxelization process in FillYZ function at line 348 :**
```CPP
inline void Voxelizer::FillYZ(const int x) {
  int ly = (*mesh_vox_lb_)[1], uy = (*mesh_vox_ub_)[1], lz = (*mesh_vox_lb_)[2],
      uz = (*mesh_vox_ub_)[2];
  unsigned int voxel_int, tmp;
  for (int y = ly, z; y <= uy; ++y) {
    for (z = lz; z <= uz; ++z) {
      voxel_int = x * size2_ + y * size_ + z;
      tmp = (voxels_.get())[voxel_int / kBatchSize].load(); // <==== Crash Happens Here
      if (GETBIT(tmp, voxel_int)) {...
```
> Access violation reading location 0x0000017519C0A000.
Crash happens right after "round 1..." appears.

And at the other side **If I apply a noise to the sphere or rotate it doesn't crash anymore and this is weird too.**

**Here's a list of tests I did :**  
```
Sphere Radius 20 			7 Crash 0 Success
Sphere Radius 11			15 Successful Try
Sphere Radius 20 With Noise		15 Successful Try
Sphere Radius 20 Rotated 		15 Successful Try
Tours Radius 50 			7 Crash 0 Success
Torus Radius 50 With Noise		15 Successful Try
Torus Radius 50 Rotated 		15 Successful Try
Sphere Radius 10			15 Successful Try
Sphere Radius 9				15 Successful Try
Sphere Radius 8				15 Successful Try
Sphere Radius 12 			7 Crash 0 Success
Sphere Radius 13 			7 Crash 0 Success
Sphere Radius 14 			7 Crash 0 Success
Remeshed Sphere				7 Crash 0 Success
Non-Symmetric Sphere 			7 Crash 0 Success
Symmetric Box 				15 Successful Try

```
I'm not sure if it be a issue from windows or platform related but maybe it can be from scale , numbers or something broke the math or memory because the same sphere with radius less than 11 works fine but when it increases and cross 11 it always crash without noise or rotation.

**Also i tried to export the sphere in different formats, typologies and results was the same and I tried windows build on 2 windows 7 and 5 windows 10 and result was the same.**

I believe it's a little issue in code not OS but maybe Mac handle it or pass it somehow and it's fixable.
If you want to make your library stable on windows I'll be happy to help, about windows you can use a free lite version (~1.5GB) of Windows 10 and a virtual machine using [VMware Fusion Free Trial](https://my.vmware.com/en/web/vmware/downloads/info/slug/desktop_end_user_computing/vmware_fusion/11_0).

Also it's possible to use TeamViewer or AnyDesk to connect to my PC and check the code.

If you wish to fix this issue for windows, I can get in touch with you with Gmail and Discord, I tried more than 10 different voxelizers and yours is the best with a good quality that's a pity to leave it like this :)

Regards,
Ultran

**Comment by topskychen** [comment]
Hi Ultran,

Thanks for testing so throughly and providing the detailed information. It should be a bounding bound bug for which I have made a fix on the latest branch v2. I have also tested on windows 7 and all three obj files work perfectly. Note that the teapot should take the mesh index 1 as I have mentioned in the last comment.

Please also have a try with more test cases. If there is still any crash, please feel free to comment and send me the file. I'd like to fix and make it better. Thanks again!

Regards,
Qian

**Comment by Bit00009** [comment]
Hi Chen,
Great job! Yes it works just fine with no errors anymore but I noticed performance became very low and surface voxelizing takes so long to finish.
```
voxelizer init...
mesh number: 1
faces : 960
vertices : 679
space: (-20.0001 -20.0001 -20.0001), (20.0001 20.0001 20.0001)
mesh bound: (-20.0001 -20.0001 -20.0001), (20.0001 20.0001 20.0001)
voxel bound: (0 0 0), (255 255 255)
done.
voxelizer initialization consumes 52.3336 ms
-------------------------------------------
surface voxelizing...
done.
surface voxelization consumes 10852.7 ms
-------------------------------------------
solid voxelizing...
round 1...
round 2...
done.
solid voxelization consumes 1877.24 ms
-------------------------------------------
writing voxels to file...
grid size : 256
lower bound : -20.0001 -20.0001 -20.0001
voxel size : 0.156251
voxel bound : (0 0 0),  (255 255 255)
wrote 8798553 voxels
writing file consumes 351.683 ms
```
And something is wired, it's happening randomly sometimes it tokes 1 sec and sometime 11 sec and sometime 10 sec but most of time it's more than 10 second for the sphere.

Regards,
Ultran

**Comment by topskychen** [comment]
Hi Ultran,

Good to hear the crash issue is gone. 

I tried all the three test files many times on both my mac and virtual windows, and all the surface tasks can be completed very fast (say 0.6s using default setting).

For instance,

```
./bin/voxelizer --input=../data/sphere.obj --output=../playground/sphere.binvox --verbose=on --mode=surface
voxelizer init...
mesh number: 1
faces : 960
vertices : 679
space: (-20.0001 -20.0001 -20.0001), (20.0001 20.0001 20.0001)
mesh bound: (-20.0001 -20.0001 -20.0001), (20.0001 20.0001 20.0001)
voxel bound: (0 0 0), (255 255 255)
done.
voxelizer initialization consumes 0.370491 s.
-------------------------------------------
surface voxelizing...
done.
surface voxelization consumes 0.576342 s.
-------------------------------------------
writing voxels to file...
dim : 256 x 256 x 256
wrote 306854 set voxels out of 16777216, in 436034 bytes
writing file consumes 0.420399 s.
```

I am wondering if you could change kThresholdBfsSurface to 0 https://github.com/topskychen/voxelizer/blob/v2/src/voxelizer.h#L32, and whether it will make any difference.

Regards,
Qian

**Comment by Bit00009** [comment]
Hi Qian,
Perfect man! Now windows version is just perfect as Mac one.

**New Benchmark :**
```
voxelizer init...
mesh number: 1
faces : 960
vertices : 679
space: (-60.0001 -60.0001 -60.0001), (60.0001 60.0001 60.0001)
mesh bound: (-60.0001 -60.0001 -60.0001), (60.0001 60.0001 60.0001)
voxel bound: (0 0 0), (255 255 255)
done.
voxelizer initialization consumes 34.6902 ms
-------------------------------------------
surface voxelizing...
done.
surface voxelization consumes 130.51 ms
-------------------------------------------
solid voxelizing...
round 1...
round 2...
done.
solid voxelization consumes 147.623 ms
-------------------------------------------
writing voxels to file...
grid size : 256
lower bound : -60.0001 -60.0001 -60.0001
voxel size : 0.468751
voxel bound : (0 0 0),  (255 255 255)
wrote 8798656 voxels
writing file consumes 29.7483 ms
```

Well, It seems random crash problem is gone and I can close the issue.
I compared some of best voxelizers and noted their best features but to keep your product issues sorted and clean, I open a new one as suggestion.

**Thanks you so much for your time and great support! <3**

Stay Safe,
Ultran
